# Generated by Django 3.2.12 on 2024-09-13 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('only_for', models.CharField(max_length=100)),
                ('pfile', models.FileField(upload_to='')),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Appoitments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_email', models.EmailField(max_length=254)),
                ('customer_email', models.EmailField(max_length=254)),
                ('select_pet', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('bookings_date_time', models.DateTimeField(auto_now=True)),
                ('appoitments_date_time', models.DateTimeField()),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('ndate_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('height', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=100)),
                ('sell_for', models.CharField(default='No', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Precautions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('pet', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_email', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(max_length=100)),
                ('reviews', models.TextField(max_length=100)),
                ('ratings', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_cares_owners_communication_systems_app.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_email', models.EmailField(max_length=254)),
                ('customer_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('prescription_file', models.FileField(upload_to='')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('appoitments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_cares_owners_communication_systems_app.appoitments')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_cares_owners_communication_systems_app.customer')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_cares_owners_communication_systems_app.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('comments', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_cares_owners_communication_systems_app.add_posts')),
            ],
        ),
        migrations.CreateModel(
            name='Pets_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_cares_owners_communication_systems_app.pet')),
            ],
            options={
                'unique_together': {('pets', 'customer_email')},
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_cares_owners_communication_systems_app.add_posts')),
            ],
            options={
                'unique_together': {('post', 'customer_email')},
            },
        ),
        migrations.CreateModel(
            name='Friends_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_cares_owners_communication_systems_app.customer')),
            ],
            options={
                'db_table': 'Friends_Requests',
                'unique_together': {('from_email', 'to_email')},
            },
        ),
    ]
